### PR TITLE
Fix plugin failing to load

### LINKED ISSUE #1: Install doesn't do anything?
Hi there! I've been using Wox for a bit and this plugin seems very nice and useful. However, every time I try to install it (`wpm install Twitch Browser`) Wox prompts me to install the plugin and restart Wox, yet when it restarts the plugin never gets installed! It doesn't appear under `wpm list`, nor Wox settings, nor the plugin folder. I've tried installing it multiple times and restarting the computer, but that doesn't seem to work. Please help!
I'm using the latest version of Wox. (1.3.524)

### PR DESCRIPTION
**Pull request by dolphinspired**
Resolves #1 - the plugin now loads correctly.

The namespace Wox.Infrastucture.* is from an internal library for Wox, not from Wox.Plugin.dll. This was causing problems when the plugin was being loaded into the app, as evidenced by the Wox log file.

## Changes

* Dropped all usage of Wox.Infrastructure.dll.
* Rebuilt the settings read/write so that it no longer needs to reference Wox.Infrastructure.dll. The Settings object now implements INotifyPropertyChanged, which will trigger a write to `{PluginDirectory}/twitch_settings.json` on any property value change.
* Added plugin.json and Images/app.png to project, repo, and build output. Now, everything in the output folder can be zipped up into a .wox file to make a working plugin!
* Bumped version number

## Testing

* Able to get expected results from `twstream`, `twtop`, and `twgames`
* Able to make changes to the plugin's settings and verify that they were changed in twitch_settings.json
* Able to close and re-open Wox to verify that settings persist

## Final steps

I've built and attached the code to save you some time. Feel free to download and try this, or re-build it from the code yourself.

1. If no more changes need to be made, download this: [WoxTwitch.zip](https://github.com/Eligioo/WoxTwitch/files/2453489/WoxTwitch.zip)
2. Change the extension to ".wox" (github won't let me upload a .wox file)
3. Click the Edit button [here](http://www.wox.one/u/497), and upload the .wox file.

### CODE REVIEW

**Comment by Eligioo** [comment]
@dolphinspired does this merge also supports Twitch's new API such that an API key is required for every request?

**Comment by Eligioo** [comment]
I uploaded version 2.2.2 to the Wox website.

**Comment by dolphinspired** [comment]
I didn't change anything with the API call, just the settings. Thanks for merging!

**Comment by Eligioo** [comment]
End of 2018 Twitch made it mandatory that API calls need their token with every request.

**Pull request merged**
